# Generated by Django 4.1.5 on 2023-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_description_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='film', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
